In [38]:
import pandas as pd 
import numpy as np
from scipy import stats 
import statsmodels.api as sm
from statsmodels.formula.api import ols
##import warnings warnings.filterwarnings('ignore')

In [39]:
pip install pytest-warnings

Note: you may need to restart the kernel to use updated packages.


In [57]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import ttest_1samp
from scipy.stats import f_oneway ##one way ANOVA
from scipy.stats import chi2_contingency
from scipy.stats import chisquare
from scipy.stats import norm
from scipy.stats import ttest_ind
from scipy.stats import ttest_rel

In [41]:
#Read csv and display the first 30 rows
import pandas as pd
iris= pd.read_csv('./Iris.csv')
count = len(iris)
iris.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Question 1: One-sample t-test on Iris dataset Task: Load the Iris dataset and test if the mean sepal length of Iris-setosa is equal to 5.0. iris = pd.read_csv('iris.csv') setosa_sepal_length = iris[iris['Species'] == 'Iris-setosa']['SepalLengthCm']

Fill in: Perform one-sample t-test
Q1: Is the mean sepal length significantly different from 5.0? (Answer: p < 0.05, so yes/no) 

In [42]:
alternative_hypothesis = "the mean sepal legnth for setosa is not 5.0"
null_hypothesis = "the mean sepal legnth for setosa is equal 5.0"

##iris
setosa_sepal_length = iris[iris['Species'] == 'Iris-setosa']['SepalLengthCm']
alpha = 0.05,
n = count
mu = 5.0

t_stats, p_value = ttest_1samp(setosa_sepal_length,mu)
print(t_stats)
print(p_value)

if p_value < alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is{null_hypothesis}')

0.12036212238318053
0.9046884777690936
we fail to reject the null hypothesis which isthe mean sepal legnth for setosa is equal 5.0


Question 2: Two-sample t-test on Iris dataset Task: Compare sepal width of Iris-setosa and Iris-versicolor. setosa_sepal_width = iris[iris['Species'] == 'Iris-setosa']['SepalWidthCm'] versicolor_sepal_width = iris[iris['Species'] == 'Iris-versicolor']['SepalWidthCm']

In [43]:
alternative_hypothesis = "the mean sepal width for setosa is  not equal to versicolor sepal width"
null_hypothesis = "the mean sepal width for setosa is equal to versicolor sepal width"

setosa_sepal_width = iris[iris['Species'] == 'Iris-setosa']['SepalWidthCm'] 
versicolor_sepal_width = iris[iris['Species'] == 'Iris-versicolor']['SepalWidthCm']

# Perform two-sample t-test (assume equal variances)
t_stat, p_value = stats.ttest_ind(setosa_sepal_width, versicolor_sepal_width, equal_var=True)
print("t-statistic:", t_stat)
print("p-value:", p_value)

if p_value < alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is{null_hypothesis}')

t-statistic: 9.282772555558111
p-value: 4.362239016010214e-15
reject null hypothesis which is the mean sepal width for setosa is equal to versicolor sepal width


Question 3: One-way ANOVA on Iris dataset Task: Test if petal length differs across all three Iris species.

Fill in: Perform one-way ANOVA
Q3: Is there a significant difference in petal length across species? (Answer: p < 0.05, so yes/no) 

In [44]:
alternative_hypothesis = 'There is a significant difference between the the mean of the petal legnths'
null_hypothesis = 'There is no significant difference between the the mean of the petal legnths'

setosa_petal_length = iris[iris['Species'] == 'Iris-setosa']['PetalLengthCm']
versicolor_petal_length = iris[iris['Species'] == 'Iris-versicolor']['PetalLengthCm']
virginica_petal_length = iris[iris['Species'] == 'Iris-virginica']['PetalLengthCm']

f_stat, p_value = f_oneway(setosa_petal_length,versicolor_petal_length , virginica_petal_length)
print("F-statistic:", f_stat)
print("p-value:", p_value)

if p_value < 0.05:
    print(f'Reject the null hypothesis which is {null_hypothesis} ')
else:
    print(f'Fail to reject the null hypothesis which is {null_hypothesis}')


F-statistic: 1179.0343277002194
p-value: 3.0519758018278374e-91
Reject the null hypothesis which is There is no significant difference between the the mean of the petal legnths 


Question 4: Chi-square test on Titanic dataset Task: Load the Titanic dataset and test if survival is independent of passenger class (Pclass). titanic = pd.read_csv('titanic.csv') contingency_table = pd.crosstab(titanic['Survived'], titanic['Pclass'])

Fill in: Perform chi-square test
Q4: Is survival independent of passenger class? (Answer: p < 0.05, so yes/no)

In [45]:
#Read csv and display the first 30 rows
import pandas as pd
titanic= pd.read_csv('./tested.csv')
count = len(titanic)
titanic.head(5)

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [46]:
alternative_hypothesis = 'There is a significant relationship between survival and passenger class'
null_hypothesis = 'There is no significant relationship between survival and passenger class '

contingency_table = pd.crosstab(titanic['Survived'], titanic['Pclass'])

##chi square test of independence
chi2, p, dof, expected = chi2_contingency(contingency_table)
print("Chi-square Statistic:", chi2)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)
print("P-value:", p)


if p < 0.05:
    print(f'Reject the null hypothesis which is {null_hypothesis} ')
else:
    print(f'Fail to reject the null hypothesis which {null_hypothesis}')


Chi-square Statistic: 6.693869422819262
Degrees of Freedom: 2
Expected Frequencies:
 [[ 68.09090909  59.18181818 138.72727273]
 [ 38.90909091  33.81818182  79.27272727]]
P-value: 0.03519206276590605
Reject the null hypothesis which is There is no significant relationship between survival and passenger class  


Question 5: One-sample z-test on Titanic dataset Task: Test if the mean age of passengers is equal to 30 (assume population std = 14.5).

Fill in: Perform one-sample z-test
Q5: Is the mean age significantly different from 30? (Answer: p < 0.05, so yes/no) 

In [47]:
alternative_hypothesis = 'mean age of passengers is equal to 30'
null_hypothesis = 'mean age of passengers is not equal to 30'

x_bar = 30 #sample mean
n = 418 ##number of passengers
sigma = 14.5 #sd of population
mu = 30 #population mean
alpha = 0.05
z = (x_bar - mu)/(sigma/np.sqrt(n))
print(z)

p_value = norm.cdf(z)
print(p_value)
if p_value <alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is {null_hypothesis}')


0.0
0.5
we fail to reject the null hypothesis which is mean age of passengers is not equal to 30


Question 6: Independent t-test on Titanic dataset Task: Compare mean age of male vs. female passengers. male_age = titanic[titanic['Sex'] == 'male']['Age'].dropna() female_age = titanic[titanic['Sex'] == 'female']['Age'].dropna()

Fill in: Perform independent t-test
Q6: Are the mean ages significantly different? (Answer: p < 0.05, so yes/no) 

In [48]:
alternative_hypothesis = "the mean ages for male and female are significantly different"
null_hypothesis = "the mean ages for male and female are significantly different"

male_age = titanic[titanic['Sex'] == 'male']['Age'].dropna()
female_age = titanic[titanic['Sex'] == 'female']['Age'].dropna()

# Perform two-sample t-test (assume equal variances)
t_stat, p_value = stats.ttest_ind(male_age, female_age, equal_var=True)
print("t-statistic:", t_stat)
print("p-value:", p_value)

if p_value < alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is {null_hypothesis}')

t-statistic: 0.000230386457754343
p-value: 0.9998163174099579
we fail to reject the null hypothesis which is the mean ages for male and female are significantly different


Question 7: One-way ANOVA on Titanic dataset Task: Test if fare differs across passenger classes (Pclass).

Fill in: Perform one-way ANOVA
Q7: Is there a significant difference in fare across classes? (Answer: p < 0.05, so yes/no) 

In [49]:
alternative_hypothesis = 'There is a significant difference in fare across classes'
null_hypothesis = 'There is no significant difference in fare across classes'

fare_class_1 = titanic[titanic['Pclass'] == '1']['Fare'].dropna()
fare_class_2 = titanic[titanic['Pclass'] == '2']['Fare'].dropna()
fare_class_3 = titanic[titanic['Pclass'] == '3']['Fare'].dropna()
f_stat, p_value = f_oneway(fare_class_1,fare_class_2, fare_class_3)
print("F-statistic:", f_stat)
print("p-value:", p_value)

if p_value < 0.05:
    print(f'Reject the null hypothesis which is {null_hypothesis} ')
else:
    print(f'Fail to reject the null hypothesis which is {null_hypothesis}')


F-statistic: nan
p-value: nan
Fail to reject the null hypothesis which is There is no significant difference in fare across classes


c:\Users\hp\anaconda3\Lib\site-packages\scipy\stats\_stats_py.py:4102: DegenerateDataWarning: at least one input has length 0
  if _f_oneway_is_too_small(samples):


Question 8: Chi-square test on Titanic dataset Task: Test if survival is independent of sex. contingency_table = pd.crosstab(titanic['Survived'], titanic['Sex'])

Fill in: Perform chi-square test
Q8: Is survival independent of sex? (Answer: p < 0.05, so yes/no) 

In [50]:
alternative_hypothesis = 'There is a significant relationship between survival and sex'
null_hypothesis = 'There is no significant relationship between survival and sex'

contingency_table = pd.crosstab(titanic['Survived'], titanic['Sex'])

##chi square test of independence
chi2, p, dof, expected = chi2_contingency(contingency_table)
print("Chi-square Statistic:", chi2)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)
print("P-value:", p)


if p < 0.05:
    print(f'Reject the null hypothesis which is {null_hypothesis} ')
else:
    print(f'Fail to reject the null hypothesis which {null_hypothesis}')

Chi-square Statistic: 413.6897405343716
Degrees of Freedom: 1
Expected Frequencies:
 [[ 96.72727273 169.27272727]
 [ 55.27272727  96.72727273]]
P-value: 5.767311139789629e-92
Reject the null hypothesis which is There is no significant relationship between survival and sex 


 Question 9: Paired t-test on Student Performance dataset Task: Load the Student Performance dataset and test if math score and reading score differ for the same students. students = pd.read_csv('StudentsPerformance.csv')

Fill in: Perform paired t-test
Q9: Are math and reading scores significantly different? (Answer: p < 0.05, so yes/no) 

In [51]:
#Read csv and display the first 30 rows
import pandas as pd
students = pd.read_csv('./StudentsPerformance.csv')
count = len(students)
students.head(5)

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [62]:
alternative_hypothesis = ('math and reading scores are significantly differebt')
null_hypothesis = ('math and reading scores are significantly different')

math_scores = students['math score']
reading_scores = students['reading score']

# Perform paired t-test
t_stat, p_value = ttest_rel(math_scores, reading_scores)

print("T-statistic:", t_stat)
print("P-value:", p_value)

if p_value < alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is {null_hypothesis}')


T-statistic: -10.816230631665421
P-value: 7.322335900414138e-26
reject null hypothesis which is math and reading scores are significantly different


Question 10: One-sample z-test on Student Performance dataset Task: Test if the mean writing score is equal to 70 (assume population std = 15).

Fill in: Perform one-sample z-test
Q10: Is the mean writing score significantly different from 70? (Answer: p < 0.05, so yes/no) 

In [60]:
alternative_hypothesis = ('the mean writting score is significantly different from 70')
null_hypothesis = ('the mean writting score is equal to 70')

 #Extract writing scores
writing_scores = students['writing score']

# Calculate sample mean and size
sample_mean = writing_scores.mean()
n = len(writing_scores)#calculating the sample size
pop_std = 15  # Given population standard deviation

# Compute z-score
z = (sample_mean - 70) / (pop_std / np.sqrt(n))

p_value = norm.cdf(z)
print(p_value)

print("Z-score:", z)
print("P-value:", p_value)

if p_value < alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is {null_hypothesis}')

2.0432999838460062e-05
Z-score: -4.1025282177917735
P-value: 2.0432999838460062e-05
reject null hypothesis which is the mean writting score is equal to 70


Question 11: Two-sample t-test on Student Performance dataset Task: Compare math scores of male vs. female students. male_math = students[students['gender'] == 'male']['math score'] female_math = students[students['gender'] == 'female']['math score']

Fill in: Perform two-sample t-test
Q11: Are math scores significantly different between genders? (Answer: p < 0.05, so yes/no) 

In [ ]:
alternative_hypothesis = "math scores are significantly different by gender"
null_hypothesis = "math scores are not significantly different by gender"

male_math = students[students['gender'] == 'male']['math score']
female_math = students[students['gender'] == 'female']['math score']

# Perform two-sample t-test (assume equal variances)
t_stat, p_value = stats.ttest_ind(male_math,female_math, equal_var=True)
print("t-statistic:", t_stat)
print("p-value:", p_value)

if p_value < alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is{null_hypothesis}')

t-statistic: 5.383245869828983
p-value: 9.120185549328822e-08
reject null hypothesis which is math scores are not significantly different by gender


Question 12: One-way ANOVA on Student Performance dataset Task: Test if math scores differ across ethnic groups (race/ethnicity).

Fill in: Perform one-way ANOVA
Q12: Is there a significant difference in math scores across ethnic groups? (Answer: p < 0.05, so yes/no)

In [ ]:
alternative_hypothesis = 'There is a significant difference in math scores across ethnic groups'
null_hypothesis = 'There is no significant difference in math scores across ethnic groups'

groupA_math = students[students['race/ethnicity'] == 'group A']['math score']
groupB_math = students[students['race/ethnicity'] == 'group B']['math score']
groupC_math = students[students['race/ethnicity'] == 'group C']['math score']
groupD_math = students[students['race/ethnicity'] == 'group D']['math score']
f_stat, p_value = f_oneway(groupA_math,groupB_math,groupC_math,groupD_math)
print("F-statistic:", f_stat)
print("p-value:", p_value)

if p_value < 0.05:
    print(f'Reject the null hypothesis which is {null_hypothesis} ')
else:
    print(f'Fail to reject the null hypothesis which is {null_hypothesis}')


F-statistic: 4.6599225222506835
p-value: 0.0030804403240573554
Reject the null hypothesis which is There is no significant difference in math scores across ethnic groups 


Question 13: Chi-square test on Student Performance dataset Task: Test if gender is independent of test preparation course completion. contingency_table = pd.crosstab(students['gender'], students['test preparation course'])

Fill in: Perform chi-square test
Q13: Is gender independent of test preparation? (Answer: p < 0.05, so yes/no) 

In [ ]:
alternative_hypothesis = 'There is a significant relationship between gender and test preparation'
null_hypothesis = 'There is no significant relationship between gender and test preparation'

contingency_table_students = pd.crosstab(students['gender'], students['test preparation course'])
##chi square test of independence
chi2, p, dof, expected = chi2_contingency(contingency_table_students)
print("Chi-square Statistic:", chi2)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)
print("P-value:", p)


if p < 0.05:
    print(f'Reject the null hypothesis which is {null_hypothesis} ')
else:
    print(f'Fail to reject the null hypothesis which {null_hypothesis}')


Chi-square Statistic: 0.015529201882465888
Degrees of Freedom: 1
Expected Frequencies:
 [[185.444 332.556]
 [172.556 309.444]]
P-value: 0.9008273880804724
Fail to reject the null hypothesis which There is no significant relationship between gender and test preparation


Question 14: One-sample t-test on Iris dataset Task: Test if the mean petal width of Iris-virginica is equal to 2.0. virginica_petal_width = iris[iris['Species'] == 'Iris-virginica']['PetalWidthCm']

Fill in: Perform one-sample t-test
Q14: Is the mean petal width significantly different from 2.0? (Answer: p < 0.05, so yes/no)

In [ ]:
alternative_hypothesis = "the mean petal width for virginica is not 2.0"
null_hypothesis = "the mean petal width for virginica is equal to 2.0"

##iris
virginica_petal_width = iris[iris['Species'] == 'Iris-virginica']['PetalWidthCm']
alpha = 0.05,
n = count
mu = 5.0

t_stats, p_value = ttest_1samp(setosa_sepal_length,mu)
print(t_stats)
print(p_value)

if p_value < alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is{null_hypothesis}')

0.12036212238318053
0.9046884777690936
we fail to reject the null hypothesis which isthe mean petal width for virginica is equal to 2.0


Question 15: Two-sample t-test on Titanic dataset Task: Compare fare paid by survivors vs. non-survivors. survivor_fare = titanic[titanic['Survived'] == 1]['Fare'].dropna() nonsurvivor_fare = titanic[titanic['Survived'] == 0]['Fare'].dropna()

Fill in: Perform two-sample t-test (assume unequal variances)
Q15: Are fares significantly different between survivors and non-survivors? (Answer: p < 0.05, so yes/no) 

In [ ]:
alternative_hypothesis = "fares are significantly different between survivors and non-survivors"
null_hypothesis = "fares are not significantly different between survivors and non-survivors"

survivor_fare = titanic[titanic['Survived'] == 1]['Fare'].dropna()
nonsurvivor_fare = titanic[titanic['Survived'] == 0]['Fare'].dropna()
# Perform two-sample t-test (assume unequal variances)
t_stat, p_value = stats.ttest_ind(survivor_fare,nonsurvivor_fare, equal_var=False)
print("t-statistic:", t_stat)
print("p-value:", p_value)

if p_value < alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is{null_hypothesis}')

t-statistic: 3.4478682983060884
p-value: 0.0006845156351814127
reject null hypothesis which is fares are not significantly different between survivors and non-survivors


Question 16: One-way ANOVA on Iris dataset Task: Test if sepal length differs across Iris species.

Fill in: Perform one-way ANOVA
Q16: Is there a significant difference in sepal length across species? (Answer: p < 0.05, so yes/no) 

In [53]:
alternative_hypothesis = 'There is a significant difference in sepal legnth across species'
null_hypothesis = 'There is no significant difference in sepal legnth across species'

setosa_sepal_legnth = iris[iris['Species'] == 'Iris-setosa']['SepalLengthCm'] 
versicolor_sepal_legnth = iris[iris['Species'] == 'Iris-versicolor']['SepalLengthCm']
virginica_sepal_legnth = iris[iris['Species'] == 'Iris-virginica']['SepalLengthCm']
print("F-statistic:", f_stat)
print("p-value:", p_value)

if p_value < 0.05:
    print(f'Reject the null hypothesis which is {null_hypothesis} ')
else:
    print(f'Fail to reject the null hypothesis which is {null_hypothesis}')

F-statistic: nan
p-value: nan
Fail to reject the null hypothesis which is There is no significant difference in sepal legnth across species


Question 17: Chi-square test on Titanic dataset Task: Test if embarkation port (Embarked) is independent of passenger class. contingency_table = pd.crosstab(titanic['Embarked'], titanic['Pclass'])

Fill in: Perform chi-square test
Q17: Is embarkation port independent of passenger class? (Answer: p < 0.05, so yes/no)

In [ ]:
alternative_hypothesis = 'There is a significant relationship between embarkation port and passenger class'
null_hypothesis = 'There is no significant relationship between embarkation port and passenger class '

contingency_table = pd.crosstab(titanic['Embarked'], titanic['Pclass'])

##chi square test of independence
chi2, p, dof, expected = chi2_contingency(contingency_table)
print("Chi-square Statistic:", chi2)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)
print("P-value:", p)


if p < 0.05:
    print(f'Reject the null hypothesis which is {null_hypothesis} ')
else:
    print(f'Fail to reject the null hypothesis which {null_hypothesis}')


Chi-square Statistic: 82.83186678873668
Degrees of Freedom: 4
Expected Frequencies:
 [[ 26.11004785  22.6937799   53.19617225]
 [ 11.77511962  10.23444976  23.99043062]
 [ 69.11483254  60.07177033 140.81339713]]
P-value: 4.373384811850251e-17
Reject the null hypothesis which is There is no significant relationship between embarkation port and passenger class  


Question 18: One-sample z-test on Student Performance dataset Task: Test if the mean math score is equal to 65 (assume population std = 15).

Fill in: Perform one-sample z-test
Q18: Is the mean math score significantly different from 65? (Answer: p < 0.05, so yes/no)

In [59]:
alternative_hypothesis = 'mean math scores is equal not to 65'
null_hypothesis = 'mean math scores is equal to 65'

math_scores = students['math score'].dropna()

x_bar = math_scores.mean() #sample mean
n = len(math_scores) ##number of students
sigma = 15 #sd of population
mu = 65 #population mean
alpha = 0.05
z = (x_bar - mu)/(sigma/np.sqrt(n))
print(z)

p_value = norm.cdf(z)
print(p_value)
if p_value <alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is {null_hypothesis}')


2.2958135812822404
0.9891567287174134
we fail to reject the null hypothesis which is mean math scores is equal to 65


Question 19: Paired t-test on Student Performance dataset Task: Test if reading score and writing score differ for the same students.

Fill in: Perform paired t-test
Q19: Are reading and writing scores significantly different? (Answer: p < 0.05, so yes/no) 

In [58]:
alternative_hypothesis = "reading and writing scores are signigicantly different"
null_hypothesis = "reading and writing scores are not signigicantly different"

writing_scores = students['writing score']
reading_scores = students['reading score']

# Perform paired t-test
t_stat, p_value = ttest_rel(writing_scores, reading_scores)

print("T-statistic:", t_stat)
print("P-value:", p_value)


if p_value < alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is{null_hypothesis}')

T-statistic: -7.787445512854921
P-value: 1.7054750946105386e-14
reject null hypothesis which is reading and writing scores are not signigicantly different


Question 20: Two-sample t-test on Iris dataset Task: Compare petal length of Iris-versicolor and Iris-virginica. versicolor_petal_length = iris[iris['Species'] == 'Iris-versicolor']['PetalLengthCm'] virginica_petal_length = iris[iris['Species'] == 'Iris-virginica']['PetalLengthCm']

Fill in: Perform two-sample t-test
Q20: Are petal lengths significantly different? (Answer: p < 0.05, so yes/no)

In [ ]:
alternative_hypothesis = "petal legnth of Iris-versicolor and Iris-virginica are significantly different "
null_hypothesis = "petal legnth of Iris-versicolor and Iris-virginica are significantly different "

versicolor_petal_length = iris[iris['Species'] == 'Iris-versicolor']['PetalLengthCm'] 
virginica_petal_length = iris[iris['Species'] == 'Iris-virginica']['PetalLengthCm']

# Perform two-sample t-test (assume equal variances)
t_stat, p_value = stats.ttest_ind(versicolor_petal_length,virginica_petal_length, equal_var=True)
print("t-statistic:", t_stat)
print("p-value:", p_value)

if p_value < alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is{null_hypothesis}')

t-statistic: -12.603779441384985
p-value: 3.1788195478061495e-22
reject null hypothesis which is petal legnth of Iris-versicolor and Iris-virginica are significantly different 


 Question 21: One-way ANOVA on Student Performance dataset Task: Test if reading scores differ across test preparation course status.

Fill in: Perform one-way ANOVA
Q21: Is there a significant difference in reading scores by test preparation? (Answer: p < 0.05, so yes/no) 

In [55]:
alternative_hypothesis = 'There is a significant difference in reading scores by test preparation'
null_hypothesis = 'There is no significant difference in reading scores by test preparation'

prep_reading = students[students['test preparation course'] == 'completed']['reading score']
noprep_reading = students[students['test preparation course'] == 'none']['reading score']
f_stat, p_value = f_oneway(prep_reading,noprep_reading)
print("F-statistic:", f_stat)
print("p-value:", p_value)

if p_value < 0.05:
    print(f'Reject the null hypothesis which is {null_hypothesis} ')
else:
    print(f'Fail to reject the null hypothesis which is {null_hypothesis}')

F-statistic: 61.96308687030073
p-value: 9.081783336895556e-15
Reject the null hypothesis which is There is no significant difference in reading scores by test preparation 


Question 22: Chi-square test on Student Performance dataset Task: Test if parental level of education is independent of test preparation course. contingency_table = pd.crosstab(students['parental level of education'], students['test preparation course'])

Fill in: Perform chi-square test
Q22: Is parental education independent of test preparation? (Answer: p < 0.05, so yes/no

In [ ]:
alternative_hypothesis = 'There is a significant relationship between parental education and test preparation'
null_hypothesis = 'There is no significant relationship between parental education and test preparation '

contingency_table = pd.crosstab(students['parental level of education'], students['test preparation course'])

##chi square test of independence
chi2, p, dof, expected = chi2_contingency(contingency_table)
print("Chi-square Statistic:", chi2)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:\n", expected)
print("P-value:", p)


if p < 0.05:
    print(f'Reject the null hypothesis which is {null_hypothesis} ')
else:
    print(f'Fail to reject the null hypothesis which {null_hypothesis}')


Chi-square Statistic: 9.54407054307069
Degrees of Freedom: 5
Expected Frequencies:
 [[ 79.476 142.524]
 [ 42.244  75.756]
 [ 70.168 125.832]
 [ 21.122  37.878]
 [ 80.908 145.092]
 [ 64.082 114.918]]
P-value: 0.08923388625809343
Fail to reject the null hypothesis which There is no significant relationship between parental education and test preparation 


 Question 23: One-sample t-test on Titanic dataset Task: Test if the mean fare is equal to 30.

Fill in: Perform one-sample t-test
Q23: Is the mean fare significantly different from 30? (Answer: p < 0.05, so yes/no) Question

In [54]:
alternative_hypothesis = "the mean fare  is not 30"
null_hypothesis = "the mean fare is equal 30"

fare = titanic['Fare'].dropna()
alpha = 0.05,
n = count
mu = 30

t_stats, p_value = ttest_1samp(fare,mu)
print(t_stats)
print(p_value)

if p_value < alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is{null_hypothesis}')


2.0553643800991495
0.04046758014596787
reject null hypothesis which is the mean fare is equal 30


24: Two-sample t-test on Student Performance dataset Task: Compare writing scores of students with vs. without test preparation. prep_writing = students[students['test preparation course'] == 'completed']['writing score'] noprep_writing = students[students['test preparation course'] == 'none']['writing score']

Fill in: Perform two-sample t-test
Q24: Are writing scores significantly different by test preparation? (Answer: p < 0.05, so yes/no)

In [ ]:
alternative_hypothesis = "writing scores are significantly different by test preparation"
null_hypothesis = "writing scores are not significantly different by test preparation"

prep_writing = students[students['test preparation course'] == 'completed']['writing score']
noprep_writing = students[students['test preparation course'] == 'none']['writing score']
# Perform two-sample t-test (assume equal variances)
t_stat, p_value = stats.ttest_ind(prep_writing,noprep_writing, equal_var=True)
print("t-statistic:", t_stat)
print("p-value:", p_value)

if p_value < alpha:
    print(f'reject null hypothesis which is {null_hypothesis}')
else:
    print(f'we fail to reject the null hypothesis which is{null_hypothesis}')

t-statistic: 10.409173436808748
p-value: 3.68529173524572e-24
reject null hypothesis which is writing scores are not significantly different by test preparation


Question 25: One-way ANOVA on Titanic dataset Task: Test if age differs across embarkation ports (Embarked).

Fill in: Perform one-way ANOVA
Q25: Is there a significant difference in age across embarkation ports? (Answer: p < 0.05, so yes/no) End of Test To complete:

Fill in the missing code for all questions. For each question, perform the specified statistical test and interpret the p-value to determine significance (alpha = 0.05). Submit your completed code and answers to the significance questions.

In [ ]:
alternative_hypothesis = 'There is a significant difference in age across embarkation ports'
null_hypothesis = 'There is no significant difference in age across embarkation ports'

port_s_age = titanic[titanic['Embarked'] == 's']['Age'].dropna()
port_Q_age = titanic[titanic['Embarked'] == 'Q']['Age'].dropna()
port_C_age = titanic[titanic['Embarked'] == 'C']['Age'].dropna()
f_stat, p_value = f_oneway(port_s_age,port_Q_age,port_C_age)
print("F-statistic:", f_stat)
print("p-value:", p_value)

if p_value < 0.05:
    print(f'Reject the null hypothesis which is {null_hypothesis} ')
else:
    print(f'Fail to reject the null hypothesis which is {null_hypothesis}')


F-statistic: nan
p-value: nan
Fail to reject the null hypothesis which is There is no significant difference in age across embarkation ports


c:\Users\hp\anaconda3\Lib\site-packages\scipy\stats\_stats_py.py:4102: DegenerateDataWarning: at least one input has length 0
  if _f_oneway_is_too_small(samples):
